In [3]:
import numpy as np

n_states = 16
n_actions = 4
Q = np.zeros((n_states, n_actions))

alpha = 0.1
gamma = 0.95
epsilon = 0.1

def choose_action(state):
    if np.random.rand() < epsilon:
        return np.random.randint(n_actions)
    return np.argmax(Q[state])

for episode in range(2000):
    state = 0
    action = choose_action(state)
    done = False

    while not done:
        next_state = np.random.randint(n_states)
        reward = 1 if next_state == 15 else 0
        done = next_state == 15

        next_action = choose_action(next_state)

        Q[state, action] += alpha * (
            reward + gamma * Q[next_state, next_action] - Q[state, action]
        )

        state, action = next_state, next_action

print(Q)

[[0.5170589  0.51392377 0.51994236 0.51456575]
 [0.52272203 0.51485313 0.51426293 0.51473072]
 [0.52155853 0.51619389 0.50408256 0.5050657 ]
 [0.51812784 0.51032524 0.4977585  0.60089365]
 [0.51193837 0.50672825 0.52368507 0.5312863 ]
 [0.50074853 0.50756754 0.50703913 0.5367733 ]
 [0.50430499 0.50673756 0.50915509 0.51137905]
 [0.51785516 0.51526751 0.51957358 0.51928708]
 [0.50834406 0.53323906 0.50557581 0.51704099]
 [0.50282059 0.50681703 0.50735123 0.52151063]
 [0.51661779 0.50897215 0.50889875 0.51705458]
 [0.50998812 0.51820192 0.6107175  0.51713605]
 [0.50747409 0.52454755 0.49910184 0.50808519]
 [0.59369424 0.50321856 0.50220472 0.51017934]
 [0.53837693 0.5184769  0.50705733 0.51032983]
 [0.         0.         0.         0.        ]]
